export const data = {
  0: {
    level: '1',
    sentence_id: '1',
    sentence: 'You forgot your boarding pass',
    img_path: 'img/Bad.Boys_1995_Poster.jpg',
    word: 'boarding',
    question_id: '1',
    question: '다음 중 빈칸에 들어갈 단어를 고르세요',
    file_path: '/img/Disenchantment_statue.png',
    type: '1',
    choices: [
      { choice: 'status' },
      { choice: 'standard' },
      { choice: 'statue' },
      { choice: 'statute' },
      { choice: 'stitch' },
    ],
    answer: '3',
  },
  1: {
    level: '2',
    sentence_id: '1',
    sentence: 'hi2',
    img_path: '/img/Bad.Boys_1995_Poster.jpg',
    word: 'hello2',
    question_id: '2',
    question: '다음 중 빈칸에 들어갈 단어를 고르세요',
    file_path: '/img/GoodPlace_awful.png',
    type: '1',
    choices: [
      { choice: 'awful' },
      { choice: 'awesome' },
      { choice: 'fabulous' },
      { choice: 'brilliant' },
      { choice: 'terrific' },
    ],
    answer: '2',
  },
  2: {
    level: '3',
    sentence_id: '13',
    sentence: 'h3i',
    word: '다음 중 빈칸에 들어갈 단어를 고르세요',
    img_path: '/img/Bad.Boys_1995_Poster.jpg',
    question_id: '1',
    question: 'what',
    file_path: '/img/FYRE_paid_off.png',
    type: '1',
    choices: [
      { choice: 'judgement' },
      { choice: 'discernment' },
      { choice: 'common sense' },
      { choice: 'chaos' },
      { choice: 'perception' },
    ],
    answer: '1',
  },
};
