"""change column type

Revision ID: 13a1456f8d14
Revises: fec473032bde
Create Date: 2021-10-14 11:35:24.744033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13a1456f8d14'
down_revision = 'fec473032bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('netflix_contents', 'content_level',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('netflix_contents', 'content_level',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
