"""empty message

Revision ID: 3c8095b93266
Revises: 43ec93d51e8d
Create Date: 2021-10-15 19:56:56.686262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8095b93266'
down_revision = '43ec93d51e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_questions', sa.Column('korean', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_questions', 'korean')
    # ### end Alembic commands ###
