"""add more levels

Revision ID: 43ec93d51e8d
Revises: 13a1456f8d14
Create Date: 2021-10-15 08:37:00.021485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ec93d51e8d'
down_revision = '13a1456f8d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_word_levels', sa.Column('level_7', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_8', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_9', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_10', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_11', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_12', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_13', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_14', sa.Integer(), nullable=False))
    op.add_column('content_word_levels', sa.Column('level_15', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_word_levels', 'level_15')
    op.drop_column('content_word_levels', 'level_14')
    op.drop_column('content_word_levels', 'level_13')
    op.drop_column('content_word_levels', 'level_12')
    op.drop_column('content_word_levels', 'level_11')
    op.drop_column('content_word_levels', 'level_10')
    op.drop_column('content_word_levels', 'level_9')
    op.drop_column('content_word_levels', 'level_8')
    op.drop_column('content_word_levels', 'level_7')
    # ### end Alembic commands ###
