"""empty message

Revision ID: 4c65b3180475
Revises: 
Create Date: 2021-10-06 15:07:56.107305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c65b3180475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentLevels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contentTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testQuestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('choice1', sa.String(length=255), nullable=True),
    sa.Column('choice2', sa.String(length=255), nullable=True),
    sa.Column('choice3', sa.String(length=255), nullable=True),
    sa.Column('choice4', sa.String(length=255), nullable=True),
    sa.Column('choice5', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netflixContents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=200), nullable=False),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('release_year', sa.String(length=5), nullable=True),
    sa.Column('running_time', sa.String(length=25), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('subs_path', sa.String(length=255), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('avg_word_difficulty', sa.Integer(), nullable=False),
    sa.Column('avg_wps', sa.Float(), nullable=False),
    sa.Column('content_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_level'], ['contentLevels.id'], ),
    sa.ForeignKeyConstraint(['type'], ['contentTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['netflixContents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    op.drop_table('netflixContents')
    op.drop_table('testQuestions')
    op.drop_table('contentTypes')
    op.drop_table('contentLevels')
    # ### end Alembic commands ###
