"""empty message

Revision ID: 65106c956410
Revises: 
Create Date: 2021-10-04 14:10:04.612278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65106c956410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netflix_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('netflix_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('running_time', sa.String(length=25), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('subs_path', sa.String(length=100), nullable=False),
    sa.Column('img_path', sa.String(length=100), nullable=False),
    sa.Column('avg_word_difficulty', sa.Integer(), nullable=False),
    sa.Column('avg_wps', sa.Float(), nullable=False),
    sa.Column('content_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netflix_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netflix_contents')
    # ### end Alembic commands ###
