"""update models

Revision ID: aac9f1d617d5
Revises: f917232606a9
Create Date: 2021-10-07 16:25:11.552725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aac9f1d617d5'
down_revision = 'f917232606a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netflix_contents', sa.Column('netflix_id', sa.String(length=20), nullable=True))
    op.add_column('netflix_contents', sa.Column('title_kr', sa.String(length=100), nullable=False))
    op.add_column('netflix_contents', sa.Column('title_en', sa.String(length=100), nullable=False))
    op.alter_column('netflix_contents', 'subs_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('netflix_contents', 'img_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('netflix_contents', 'word_difficulty_level',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('netflix_contents', 'words_per_second',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('netflix_contents', 'content_level',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('netflix_contents', 'content_level',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('netflix_contents', 'words_per_second',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('netflix_contents', 'word_difficulty_level',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('netflix_contents', 'img_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('netflix_contents', 'subs_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('netflix_contents', 'title_en')
    op.drop_column('netflix_contents', 'title_kr')
    op.drop_column('netflix_contents', 'netflix_id')
    # ### end Alembic commands ###
