"""migrate

Revision ID: cb066b4d4805
Revises: 
Create Date: 2021-10-07 18:59:14.886495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb066b4d4805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('choice1', sa.String(length=255), nullable=True),
    sa.Column('choice2', sa.String(length=255), nullable=True),
    sa.Column('choice3', sa.String(length=255), nullable=True),
    sa.Column('choice4', sa.String(length=255), nullable=True),
    sa.Column('choice5', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netflix_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('netflix_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('title_kr', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=200), nullable=False),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('running_time', sa.String(length=25), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('subs_path', sa.String(length=255), nullable=False),
    sa.Column('img_path', sa.String(length=255), nullable=False),
    sa.Column('word_difficulty_level', sa.Integer(), nullable=True),
    sa.Column('words_per_second', sa.Float(), nullable=True),
    sa.Column('content_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_level'], ['content_levels.id'], ),
    sa.ForeignKeyConstraint(['type'], ['content_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['netflix_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    op.drop_table('netflix_contents')
    op.drop_table('test_questions')
    op.drop_table('content_types')
    op.drop_table('content_levels')
    # ### end Alembic commands ###
