"""add models

Revision ID: d0bd1386ab98
Revises: 65106c956410
Create Date: 2021-10-04 16:25:38.801158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0bd1386ab98'
down_revision = '65106c956410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentLevels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contentTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testQuestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('choice1', sa.String(length=255), nullable=False),
    sa.Column('choice2', sa.String(length=255), nullable=False),
    sa.Column('choice3', sa.String(length=255), nullable=False),
    sa.Column('choice4', sa.String(length=255), nullable=False),
    sa.Column('choice5', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordDifficultyLevels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netflixContents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('netflix_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('running_time', sa.String(length=25), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('subs_path', sa.String(length=100), nullable=False),
    sa.Column('img_path', sa.String(length=100), nullable=False),
    sa.Column('avg_word_difficulty', sa.Integer(), nullable=False),
    sa.Column('avg_wps', sa.Float(), nullable=False),
    sa.Column('content_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avg_word_difficulty'], ['wordDifficultyLevels.id'], ),
    sa.ForeignKeyConstraint(['content_level'], ['contentLevels.id'], ),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['type'], ['contentTypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netflix_id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['netflixContents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('netflix_id', table_name='netflix_contents')
    op.drop_table('netflix_contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netflix_contents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('netflix_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('genre', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('running_time', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('story', mysql.TEXT(), nullable=True),
    sa.Column('subs_path', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('img_path', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('avg_word_difficulty', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_wps', mysql.FLOAT(), nullable=False),
    sa.Column('content_level', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('netflix_id', 'netflix_contents', ['netflix_id'], unique=False)
    op.drop_table('sentences')
    op.drop_table('netflixContents')
    op.drop_table('wordDifficultyLevels')
    op.drop_table('testQuestions')
    op.drop_table('genres')
    op.drop_table('contentTypes')
    op.drop_table('contentLevels')
    # ### end Alembic commands ###
