"""add more tables

Revision ID: f8b35e765d26
Revises: cb066b4d4805
Create Date: 2021-10-11 11:05:18.581455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b35e765d26'
down_revision = 'cb066b4d4805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['netflix_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_unique_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['netflix_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_word_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('level_1', sa.Integer(), nullable=False),
    sa.Column('level_2', sa.Integer(), nullable=False),
    sa.Column('level_3', sa.Integer(), nullable=False),
    sa.Column('level_4', sa.Integer(), nullable=False),
    sa.Column('level_5', sa.Integer(), nullable=False),
    sa.Column('level_6', sa.Integer(), nullable=False),
    sa.Column('wps', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['netflix_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sentences', sa.Column('start', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'start')
    op.drop_table('content_word_levels')
    op.drop_table('content_unique_words')
    op.drop_table('content_hashtags')
    # ### end Alembic commands ###
