"""delete content_level

Revision ID: fec473032bde
Revises: f8b35e765d26
Create Date: 2021-10-13 01:09:17.221547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "fec473032bde"
down_revision = "f8b35e765d26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "netflix_contents_ibfk_1", "netflix_contents", type_="foreignkey"
    )
    op.drop_table("content_levels")
    op.add_column(
        "content_word_levels", sa.Column("wps_weight", sa.Float(), nullable=False)
    )
    op.create_unique_constraint(None, "content_word_levels", ["content_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "netflix_contents_ibfk_1",
        "netflix_contents",
        "content_levels",
        ["content_level"],
        ["id"],
    )
    op.drop_constraint(None, "content_word_levels", type_="unique")
    op.drop_column("content_word_levels", "wps_weight")
    op.create_table(
        "content_levels",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("level", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
